const Promise = require('bluebird')

exports.seed = (knex, Promise) => {
      return Promise.join(
        knex('posts_tags').del(),
        knex('posts').del(),
        knex('tags').del(),
        knex('categories').del(),
        knex('followers_following').del(),
        knex('post_stars').del(),
        knex('users').del(),

        knex('users').insert({id: 1, username: 'sevda', email: 'sevda@g.com', password: '123', twitterLink: 'sevda_tw',
        openness: 0.60  ,conscientiousness: 0.10, extraversion: 0.40, agreeableness: 0.20, emotionalRange: 0.80}),
        knex('users').insert({id: 2, username: 'isaac', email: 'isaac@g.com', password: '123', twitterLink: 'isaac_tw',
        openness: 0.35 ,conscientiousness: 0.25, extraversion: 0.70, agreeableness: 0.45, emotionalRange: 0.55}),
        knex('users').insert({id: 3, username: 'wasiff', email: 'wassiff@g.com', password: '123',  twitterLink: 'wasiff_tw',
        openness: 0.90 ,conscientiousness: 0.49, extraversion: 0.58, agreeableness: 0.15, emotionalRange: 0.82}),
        knex('users').insert({id: 4, username: 'elliott', email: 'elliott@g.com', password: '123',  twitterLink: 'eliott',
        openness: 0.93 ,conscientiousness: 0.69, extraversion: 0.78, agreeableness: 0.65, emotionalRange: 0.92}),
        knex('users').insert({id: 5, username: 'dan', email: 'dan@g.com', password: '123',  twitterLink: 'dan_tw',
        openness: 0.30 ,conscientiousness: 0.49, extraversion: 0.58, agreeableness: 0.54, emotionalRange: 0.82}),
        knex('users').insert({id: 6, username: 'eric', email: 'eric@g.com', password: '123',  twitterLink: 'eric_tw',
        openness: 0.80 ,conscientiousness: 0.39, extraversion: 0.18, agreeableness: 0.92, emotionalRange: 0.72}),
        knex('users').insert({id: 7, username: 'val', email: 'val@g.com', password: '123',  twitterLink: 'val_tw',
        openness: 0.90 ,conscientiousness: 0.79, extraversion: 0.28, agreeableness: 0.22, emotionalRange: 0.82}),
        knex('users').insert({id: 8, username: 'nate', email: 'ate@g.com', password: '123',  twitterLink: 'at_tw',
        openness: 0.20 ,conscientiousness: 0.99, extraversion: 0.38, agreeableness: 0.21, emotionalRange: 0.52}),
        knex('users').insert({id: 9, username: 'collin', email: 'col@g.com', password: '123',  twitterLink: 'collin_tw',
        openness: 0.30 ,conscientiousness: 0.49, extraversion: 0.58, agreeableness: 0.20, emotionalRange: 0.42}),
        knex('users').insert({id: 10, username: 'alisa', email: 'alisa@g.com', password: '123',  twitterLink: 'alisa_tw',
        openness: 0.40 ,conscientiousness: 0.39, extraversion: 0.98, agreeableness: 0.19, emotionalRange: 0.92}),
        knex('users').insert({id: 11, username: 'neil', email: 'neil@g.com', password: '123',  twitterLink: 'nico_tw',
        openness: 0.50 ,conscientiousness: 0.79, extraversion: 0.88, agreeableness: 0.18, emotionalRange: 0.82}),
        knex('users').insert({id: 12, username: 'paul', email: 'paul@g.com', password: '123',  twitterLink: 'paul_tw',
        openness: 0.60 ,conscientiousness: 0.29, extraversion: 0.78, agreeableness: 0.17, emotionalRange: 0.72}),
        knex('users').insert({id: 13, username: 'ben', email: 'ben@g.com', password: '123',  twitterLink: 'ben_tw',
        openness: 0.70 ,conscientiousness: 0.39, extraversion: 0.68, agreeableness: 0.16, emotionalRange: 0.62}),
        knex('users').insert({id: 14, username: 'nikshila', email: 'nic@g.com', password: '123',  twitterLink: 'nic_tw',
        openness: 0.80 ,conscientiousness: 0.29, extraversion: 0.58, agreeableness: 0.15, emotionalRange: 0.52}),
        knex('users').insert({id: 15, username: 'barktek', email: 'bartek@g.com', password: '123',  twitterLink: 'bartek_tw',
        openness: 0.90 ,conscientiousness: 0.79, extraversion: 0.48, agreeableness: 0.14, emotionalRange: 0.42}),
        knex('users').insert({id: 16, username: 'whiteshadow', email: 'whiteshadow@g.com', password: '123',  twitterLink: 'ws_tw',
        openness: 0.01 ,conscientiousness: 0.01, extraversion: 0.01, agreeableness: 0.13, emotionalRange: 0.32}),
        knex('users').insert({id: 17, username: 'bei', email: 'bei@g.com', password: '123',  twitterLink: 'bei_tw',
        openness: 0.30 ,conscientiousness: 0.49, extraversion: 0.38, agreeableness: 0.12, emotionalRange: 0.22}),


       knex('followers_following').insert({id: 1, follower_id: 1, followed_id: 3}),
       knex('followers_following').insert({id: 2, follower_id: 2, followed_id: 3}),
       knex('followers_following').insert({id: 3, follower_id: 3, followed_id: 2}),
       knex('followers_following').insert({id: 4, follower_id: 4, followed_id: 1}),
       knex('followers_following').insert({id: 5, follower_id: 5, followed_id: 1}),
       knex('followers_following').insert({id: 6, follower_id: 5, followed_id: 2}),
       knex('followers_following').insert({id: 7, follower_id: 5, followed_id: 3}),
       knex('followers_following').insert({id: 8, follower_id: 6, followed_id: 3}),
       knex('followers_following').insert({id: 9, follower_id: 7, followed_id: 4}),
       knex('followers_following').insert({id: 10, follower_id: 8, followed_id: 5}),
       knex('followers_following').insert({id: 11, follower_id: 9, followed_id: 6}),
       knex('followers_following').insert({id: 12, follower_id: 10, followed_id: 7}),
       knex('followers_following').insert({id: 13, follower_id: 11, followed_id: 8}),
       knex('followers_following').insert({id: 14, follower_id: 12, followed_id: 9}),
       knex('followers_following').insert({id: 15, follower_id: 13, followed_id: 10}),
       knex('followers_following').insert({id: 16, follower_id: 14, followed_id: 11}),
       knex('followers_following').insert({id: 17, follower_id: 15, followed_id: 11}),
       knex('followers_following').insert({id: 18, follower_id: 16, followed_id: 13}),
       knex('followers_following').insert({id: 19, follower_id: 17, followed_id: 13}),
       knex('followers_following').insert({id: 20, follower_id: 17, followed_id: 5}),


        knex('categories').insert({id: 1, name: 'coffee'}),
        knex('categories').insert({id: 2, name: 'software'}),
        knex('categories').insert({id: 3, name: 'food'}),
        knex('categories').insert({id: 4, name: 'business ventures'}),
        knex('categories').insert({id: 5, name: 'renting'}),
        knex('categories').insert({id: 6, name: 'concert'}),
        knex('categories').insert({id: 7, name: 'movies'}),
        knex('categories').insert({id: 8, name: 'jobs'}),
        knex('categories').insert({id: 9, name: 'developers'}),
        knex('categories').insert({id: 10, name: 'startups'}),
        knex('categories').insert({id: 11, name: 'meetups'}),
        knex('categories').insert({id: 12, name: 'for sale'}),
        knex('categories').insert({id: 13, name: 'buying'}),


        knex('tags').insert({id: 1, name: 'instant'}),
        knex('tags').insert({id: 2, name: 'react'}),
        knex('tags').insert({id: 3, name: 'jquery'}),
        knex('tags').insert({id: 4, name: 'angular'}),
        knex('tags').insert({id: 5, name: 'js'}),
        knex('tags').insert({id: 6, name: 'pinkfloyd'}),
        knex('tags').insert({id: 7, name: 'peets'}),
        knex('tags').insert({id: 8, name: 'starbucks'}),
        knex('tags').insert({id: 9, name: 'javascript'}),
        knex('tags').insert({id: 10, name: 'css'}),
        knex('tags').insert({id: 11, name: 'redux'}),
        knex('tags').insert({id: 12, name: 'room'}),
        knex('tags').insert({id: 13, name: 'pizza'}),
        knex('tags').insert({id: 14, name: 'clothing'}),
        knex('tags').insert({id: 15, name: 'hackathon'}),
        knex('tags').insert({id: 16, name: 'burgers'}),
        knex('tags').insert({id: 17, name: 'engineering'}),
        knex('tags').insert({id: 18, name: 'oasis'}),
        knex('tags').insert({id: 19, name: 'code'}),

        knex('posts').insert({id: 1, content: "Rendezvous at mark six point one. This is Red Two. Flying toward you. Red Three, standing by. Red Leader, this is Base One. Keep half your group out of range for the next run. Copy, Base One. Luke, take Red Two and Three. Hold up here and wait for my signal...to start your run. This is it! We should be able to see it by now. Keep your eyes open for those fighters! There's too much interference! Red Five, can you see them from where you are? No sign of any...wait! Coming in point three five. I see them. I'm in range. Target's coming up! Just hold them off for a few seconds.", title: 'Red Five', user_id: 1, category_id: 1}),
        knex('posts').insert({id: 2, content: "And what of the Rebellion? If the Rebels have obtained a complete technical readout of this station, it is possible, however unlikely, that they might find a weakness and exploit it. The plans you refer to will soon be back in our hands. Any attack made by the Rebels against this station would be a useless gesture, no matter what technical data they've obtained. This station is now the ultimate power in the universe. I suggest we use it!", title: 'Rebel!', user_id: 1, category_id:1}),
        knex('posts').insert({id: 3, content: "Learn about the Force, Luke. Look, I can take you as far as Anchorhead. You can get a transport there to Mos Eisley or wherever you're going. You must do what you feel is right, of course.", title: 'The Force', user_id: 2, category_id: 2}),
        knex('posts').insert({id: 4, content: "That malfunctioning little twerp. This is all his fault! He tricked me into going this way, but he'll do no better. Wait, what's that? A transport! I'm saved! Over here! Help! Please, help! Artoo-Detoo! It's you! It's you!", title: 'What is a closure?', user_id: 3, category_id: 2}),
        knex('posts').insert({id: 5, content: "What is it? I'm afraid I'm not quite sure, sir. He says I found her, and keeps repeating, She's here. Well, who...who has he found? Princess Leia. The princess? She's here? Princess? What's going on? Level five. Detention block A A-twenty-three. I'm afraid she's scheduled to be terminated. Oh, no! We've got to do something. What are you talking about? The droid belongs to her. She's the one in the message.. We've got to help her. Now, look, don't get any funny ideas. The old man wants us to wait right here. But he didn't know she was here. Look, will you just find a way back into the detention block?", title: 'You Dont know JS', user_id: 4, category_id: 3}),
        knex('posts').insert({id: 6, content: "Yes. Our scout ships have reached Dantooine. They found the remains of a Rebel base, but they estimate that it has been deserted for some time. They are now conducting an extensive search of the surrounding systems. She lied! She lied to us! I told you she would never consciously betray the Rebellion. Terminate her...immediately!", title: 'Dantooine', user_id: 5, category_id: 8}),
        knex('posts').insert({id: 7, content: "He says the restraining bolt has short circuited his recording system. He suggests that if you remove the bolt, he might be able to play back the entire recording. H'm? Oh, yeah, well, I guess you're too small to run away on me if I take this off! Okay. There you go. Well, wait a minute. Where'd she go? Bring her back! Play back the entire message. What message? The one you're carrying inside your rusty innards! Luke? Luke! Come to dinner! All right, I'll be right there, Aunt Beru. I'm sorry, sir, but he appears to have picked up a slight flutter. Well, see what you can do with him. I'll be right back. Just you reconsider playing that message for him. No, I don't think he likes you at all. No, I don't like you either.", title: 'The bad parts', user_id: 6, category_id: 9}),
        knex('posts').insert({id: 8, content: "The approach will not be easy. You are required to maneuver straight down this trench and skim the surface to this point. The target area is only two meters wide. It's a small thermal exhaust port, right below the main port. The shaft leads directly to the reactor system. A precise hit will start a chain reaction which should destroy the station. Only a precise hit will set up a chain reaction. The shaft is ray-shielded, so you'll have to use proton torpedoes. That's impossible, even for a computer. It's not impossible. I used to bull's-eye womp rats in my T-sixteen back home. They're not much bigger than two meters. Man your ships! And may the Force be with you!", title: 'Proton Torpedoes', user_id: 7, category_id: 10}),
        knex('posts').insert({id: 9, content: "Hey...hey, open the pressure maintenance hatch on unit number... where are we? Three-two-six-eight-two-seven. If we can just avoid any more female advice, we ought to be able to get out of here. Well, let's get moving! Where are you going? No, wait. They'll hear! Come here, you big coward! Chewie! Come here! Listen. I don't know who you are, or where you came from, but from now on, you do as I tell you. Okay? Look, Your Worshipfulness, let's get one thing straight! I take orders from one person! Me! It's a wonder you're still alive. Will somebody get this big walking carpet out of my way? No reward is worth this.", title: 'Return NULL', user_id: 8, category_id: 3}),
        knex('posts').insert({id: 10, content: "We count thirty Rebel ships, Lord Vader. But they're so small they're evading our turbo-lasers! We'll have to destroy them ship to ship. Get the crews to their fighters. Luke, let me know when you're going in. I'm on my way in now... Watch yourself! There's a lot of fire coming from the right side of that deflection tower. I'm on it. Squad leaders, we've picked up a new group of signals. Enemy fighters coming your way.", title: 'Lord Vader', user_id: 9, category_id: 7}),
        knex('posts').insert({id: 11, content: "I can't see a thing in this helmet. This is not going to work. Why didn't you say so before? I did say so before! Where are you taking this...thing? Prisoner transfer from Block one-one-three-eight. I wasn't notified. I'll have to clear it. Look out! We've got to find out which cell this princess of yours is in. Here it is...cell twenty-one-eight-seven. You go get her. I'll hold them here. Everything is under control. Situation normal. What happened? Uh...had a slight weapons malfunction. But, uh, everything's perfectly all right now. We're fine. We're all fine here, now, thank you. How are you? We're sending a squad up. Uh, uh, negative. We had a reactor leak here now. Give us a few minutes to lock it down. Large leak...very dangerous. Who is this? What's your operating number? Boring conversation anyway. Luke! We're going to have company!",title: 'This helmet', user_id: 10, category_id: 12}),
        knex('posts').insert({id: 12, content: "You must come along now, Artoo. There's really nothing more we can do. And my joints are freezing up. Don't say thing like that! Of course we'll see Master Luke again. He'll be quite all right, you'll see. Stupid little short-circuit. He'll be quite all right. Sir, all the patrols are in. There's still no contact from Skywalker or Solo. Mistress Leia, Artoo says he's been quite unable to pick up any signals, although he does admit that his own range is far too weak to abandon all hope. Your Highness, there's nothing more we can do tonight. The shield doors must be closed. Close the doors. Yes, sir.", title: 'From Skywalker', user_id: 11, category_id: 13}),
        knex('posts').insert({id: 13, content: "Rouge Group, use your harpoons and tow cables. Go for the legs. It might be our only chance of stopping them. All right, stand by, Dack. Luke, we've got a malfunction in fire control. I'll have to cut in the auxiliary. ust hang on. Hang on, Dack. Get ready to fire that tow cable. Dack? Dack! Yes, Lord Vader. I've reached the main power generator. The shield will be down in moments. You may start your landing. Rouge Three. Copy, Rouge Leader Wedge, I've lost my gunner. You'll have to make this shot. I'll cover for you. Set your harpoon. Follow me on the next pass. oming around, Rouge Leader.", title: 'Use your harpoons', user_id: 12, category_id: 5}),
        knex('posts').insert({id: 14, content: "Ah, good. New acquisitions. You are a protocol droid, are you not? I am See-Threepio, human-cy... Yes or no will do. Oh. Well, yes. How many languages do you speak? I am fluent in over six million forms of communication, and can readily... Splendid! We have been without an interpreter since our master got angry with our last protocol droid and disintegrated him. Disintegrated? Guard! This protocol droid might be useful. Fit him with a restraining bolt and take him back to His Excellency's main audience chamber. Artoo, don't leave me! Ohhh! You're a feisty little one, but you'll soon learn some respect. I have need for you on the master's Sail Barge. And I think you'll fit in nicely.", title: 'Protocol Droids', user_id: 13, category_id: 3}),
        knex('posts').insert({id: 15, content: "If they don't go for this, we're gonna have to get outta here pretty quick, Chewie. We have you on our screen now. Please identify. Shuttle Tydirium requesting deactivation of the deflector shield. Shuttle Tydirium, transmit the clearance code for shield passage. Transmission commencing. Now we find out if that code is worth the price we paid. It'll work. It'll work. Vader's on that ship. Now don't get jittery, Luke. There are a lot of command ships. Keep your distance though, Chewie, but don't look like you're trying to keep your distance. I don't know. Fly casual. I'm endangering the mission. I shouldn't have come. It's your imagination, kid. Come on. Let's keep a little optimism here.", title: 'Shuttle Tydrirum', user_id: 17, category_id: 1}),
        knex('posts').insert({id: 16, content: "You're free of the carbonite. Shhh. You have hibernation sickness. I can't see. Your eyesight will return in time. Where am I? Jabba's palace. Who are you? Someone who loves you. Leia! I gotta get you out of here. What's that? I know that laugh. Hey, Jabba. Look, Jabba, I was just on my way to pay you back, but I got a little sidetracked. It's not my fault. It's too late for that, Solo. You may have been a good smuggler, but now you're Bantha fodder. Look... Take him away! Jabba... I'll pay you triple! You're throwing away a fortune here. Don't be a fool! Bring her to me.", title: 'Dont be a fool', user_id: 15, category_id: 3}),
        knex('posts').insert({id: 17, content: "I think my eyes are getting better. Instead of a big dark blur, I see a big light blur. There's nothing to see. I used to live here, you know. You're gonna die here, you know. Convenient. Just stick close to Chewie and Lando. I've taken care of everything. Oh... great! Soon you will learn to appreciate me. Oh, I'm terribly sor... Artoo! What are you doing here? Well, I can see you're serving drinks, but this place is dangerous. They're going to execute Master Luke and, if we're not careful, us too! Hmm. I wish I had your confidence. Victims of the almighty Sarlacc: His Excellency hopes that you will die honorably. But should any of you wish to beg for mercy, the great Jabba the Hutt will now listen to your pleas.", title: 'Soon...you will learn to appreciate', user_id: 1, category_id: 4}),
        knex('posts').insert({id: 18, content: "Echo Three to Echo Seven. Han, old buddy, do you read me? Loud and clear, kid. What's up? Well, I finished my circle. I don't pick up any life readings. There isn't enough life on this ice cube to fill a space cruiser. The sensors are placed. I'm going back. Right. I'll see you shortly. There's a meteorite that hit the ground near here. I want to check it out. It won't take long. Hey, steady girl. What's the matter? You smell something?", title: 'Echo Echo', user_id: 10, category_id: 5}),
        knex('posts').insert({id: 19, content: "Noisy brute. Why don't we just go into light-speed? We can't? How would you know the hyperdrive is deactivated? The city's central computer told you? Artoo-Detoo, you know better than to trust a strange computer. Ouch! Pay attention to what you're doing!", title: 'Hyperdrive deactivated', user_id: 9, category_id: 7}),
        knex('posts').insert({id: 20, content: "Don't try to blame me. I didn't ask you to turn on the thermal heater. I merely commented that it was freezing in the princess's chamber. But it's supposed to be freezing. How are we going to dry out all her clothes? I really don't know. Oh, switch off. Why do you take this apart now? I'm trying to get us out of here and you pull both of these. Excuse me, sir. Put them back together right now. Might I have a word with you, please?", title: 'Atomic operations', user_id: 8, category_id: 8}),
        knex('posts').insert({id: 21, content: "Concentrate...feel the Force flow. Yes. Good. Calm, yes. Through the Force, things you will see. Other places. The future...the past. Old friends long gone. Han! Leia! Hmm. Control, control. You must learn control. I saw...I saw a city in the clouds. Mmm. Friends you have there. They were in pain. It is the future you see. Future? Will they die? Difficult to see. Always in motion is the future. I've got to go to them. Decide you must how to serve them best. If you leave now, help them you could. But you would destroy all for which they have fought and suffered.", title: 'Things you will see', user_id: 6, category_id: 9}),
        knex('posts').insert({id: 22, content: "Run! Yes. A Jedi's strength flows from the Force. But beware of the dark side. Anger...fear...aggression. The dark side of the Force are they. Easily they flow, quick to join you in a fight. If once you start down the dark path, forever will it dominate your destiny, consume you it will, as it did Obi-Wan's apprentice. Vader. Is the dark side stronger? No...no...no. Quicker, easier, more seductive. But how am I to know the good side from the bad? You will know. When you are calm, at peace. Passive. A Jedi uses the Force for knowledge and defense, never for attack. But tell me why I can't... No, no, there is no why. Nothing more will I teach you today. Clear your mind of questions. Mmm. Mmmmmm.", title: 'Beware...', user_id: 11, category_id: 10}),
        knex('posts').insert({id: 23, content: "Hmm. That face you make. Look I so old to young eyes? No... of course not. I do, yes, I do! Sick have I become. Old and weak. When nine hundred years old you reach, look as good you will not. Hmm? Soon will I rest. Yes, forever sleep. Earned it, I have. Master Yoda, you can't die. Strong am I with the Force... but not that strong! Twilight is upon me and soon night must fall. That is the way of things... the way of the Force. But I need your help. I've come back to complete the training. No more training do you require. Already know you that which you need. Then I am a Jedi? Ohhh. Not yet. One thing remains: Vader. You must confront Vader. Then, only then, a Jedi will you be. And confront him you will.", title: 'Strong am I with the Force', user_id: 14, category_id: 11}),
        knex('posts').insert({id: 24, content: "Luke, help me take this mask off. But you'll die. Nothing can stop that now. Just for once... let me look on you with my own eyes. Now...go, my son. Leave me. No. You're coming with me. I can't leave you here. I've got to save you. You already have, Luke. You were right about me. Tell your sister...you were right. Father...I won't leave you. There it is! All right, Wedge. Go for the power regulator on the north tower. Copy, Gold Leader. I'm already on my way out. Move the fleet away from the Death Star.", title: 'I am your Father', user_id: 16, category_id: 12}),
        knex('posts').insert({id: 25, content: "You are beaten. It is useless to resist. Don't let yourself be destroyed as Obi-Wan did. There is no escape. Don't make me destroy you. You do not yet realize your importance. You have only begun to discover you power. Join me and I will complete your training. With our combined strength, we can end this destructive conflict and bring order to the galaxy. I'll never join you! If you only knew the power of the dark side. Obi-Wan never told you what happened to your father. He told me enough! He told me you killed him. No. I am your father. No. No. That's not true! That's impossible! Search your feelings. You know it to be true. No! No! No! Luke. You can destroy the Emperor. He has foreseen this. It is your destiny. Join me, and we can rule the galaxy as father and son. Come with me. It's the only way.", title: 'Hack Reactor Obi-Wan', user_id: 15, category_id: 11}),
        knex('posts').insert({id: 26, content: "Groups seven and ten will stay behind to fly the speeders. As soon as each transport is loaded, evacuation control will give clearance for immediate launch. Right, sir. Okay, that's it. Try it...Off! Turn it off! Turn it off! Off! Sir, it will take quite awhile to evacuate the T-forty-sevens. Well, forget the heavy equipment. There's plenty of time to get the smaller modules on the transports. Take care, sir. Thanks. Chewie, take care of yourself, okay? Hi, kid. There's got to be a reason for it. Check it at the other end. Wait a second. You all right? Yeah. Be careful. You, too.Reroute all power to the energy shield. We've got to hold them till all transports are away. Prepare for ground assault.", title: 'T-forty-sevens', user_id: 14, category_id: 12}),
        knex('posts').insert({id: 27, content: "Run! Yes. A Jedi's strength flows from the Force. But beware of the dark side. Anger...fear...aggression. The dark side of the Force are they. Easily they flow, quick to join you in a fight. If once you start down the dark path, forever will it dominate your destiny, consume you it will, as it did Obi-Wan's apprentice. Vader. Is the dark side stronger? No...no...no. Quicker, easier, more seductive. But how am I to know the good side from the bad? You will know. When you are calm, at peace. Passive. A Jedi uses the Force for knowledge and defense, never for attack. But tell me why I can't... No, no, there is no why. Nothing more will I teach you today. Clear your mind of questions. Mmm. Mmmmmm.", title: 'Mmmmmm', user_id: 12, category_id: 13}),
        


        knex('posts_tags').insert({id: 1, post_id: 1, tag_id: 1}),
        knex('posts_tags').insert({id: 2, post_id: 2, tag_id: 2}),
        knex('posts_tags').insert({id: 3, post_id: 3, tag_id: 7}),
        knex('posts_tags').insert({id: 4, post_id: 4, tag_id: 5}),
        knex('posts_tags').insert({id: 5, post_id: 5, tag_id: 4}),
        knex('posts_tags').insert({id: 6, post_id: 5, tag_id: 5}),
        knex('posts_tags').insert({id: 7, post_id: 5, tag_id: 7}),
        knex('posts_tags').insert({id: 8, post_id: 7, tag_id: 9}),
        knex('posts_tags').insert({id: 9, post_id: 8, tag_id: 10}),
        knex('posts_tags').insert({id: 10, post_id: 9, tag_id: 11}),
        knex('posts_tags').insert({id: 11, post_id: 10, tag_id: 12}),
        knex('posts_tags').insert({id: 12, post_id: 11, tag_id: 13}),
        knex('posts_tags').insert({id: 13, post_id: 12, tag_id: 14}),
        knex('posts_tags').insert({id: 14, post_id: 13, tag_id: 3}),

        knex('posts_stars').insert({star_id: 1, user_id: 3}),
        knex('posts_stars').insert({star_id: 4, user_id: 3}),
        knex('posts_stars').insert({star_id: 3, user_id: 2}),
        knex('posts_stars').insert({star_id: 4, user_id: 1}),
        knex('posts_stars').insert({star_id: 5, user_id: 1}),
        knex('posts_stars').insert({star_id: 5, user_id: 5}),
        knex('posts_stars').insert({star_id: 5, user_id: 3}),
        
      )
      .then((seed) => {
        console.log(`Seeded db with ${seed.length} entries.`)
      })
      .catch((err) => {
        console.log(`Error: ${err}`)
      })
}  
