export const CREATE_NEW_POST = 'CREATE_NEW_POST';
export const UPDATE_POST = 'UPDATE_POST';
export const DELETE_POST = 'DELETE_POST';
export const FETCH_ALL_POSTS = 'FETCH_ALL_POSTS';
export const FETCH_USER_POSTS = 'FETCH_USER_POSTS';
export const FETCH_PUBLIC_POSTS = 'FETCH_PUBLIC_POSTS';
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const ADD_TAG = 'ADD_TAG'
export const REMOVE_TAG = 'REMOVE_TAG'
export const CLEAR_TAGS = 'CLEAR_TAGS'
export const SET_USER = 'SET_USER'
export const LOGOUT_USER = 'LOGOUT_USER'
export const REFRESH_STATS = 'REFRESH_STATS';
export const FILTER_POSTS = 'FILTER_POSTS'
export const CLEAR_POSTS = 'CLEAR_POSTS'
export const SET_MATCHES = 'SET_MATCHES'
export const CLEAR_MATCHES = 'CLEAR_MATCHES'
export const SET_TWITTER = 'SET_TWITTER'
export const INIT_PERSONALITY_MATCHES = 'INIT_PERSONALITY_MATCHES'
export const CLEAR_PERSONALITY_MATCHES = 'CLEAR_PERSONALITY_MATCHES'
export const FOLLOW_USER = 'FOLLOW_USER'
export const SHOW_FOLLOWERS = 'SHOW_FOLLOWERS'
export const SHOW_FOLLOWING = 'SHOW_FOLLOWING'


